name: 'webchat-bot-action'
description: 'wechat bot message'
inputs:
  wechat_bot_url:
    description: 'wechat bot url'
    required: true
    default: ''
  type: 
    description: 'wechat message type'
    required: false
    default: 'markdown'
  content:
    description: 'wechat message content'
    required: true
    default: ''
outputs:
  res:
    description: ''
  err:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
